name: Environment test
on:
  push:
    tags:
      - 'test-*'

jobs:
  notify:
    name: Notification job
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}

    steps:
      - name: Get vars
        id: vars
        run: |
          echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Notify in Slack
        uses: slackapi/slack-github-action@v1.15.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: |
            Tag [${{ steps.vars.outputs.tag }}](https://github.com/${{ github.repository }}/releases/tag/${{ steps.vars.outputs.tag }}) of ${{ github.repository }} is ready to deploy!

            Approvers, [go review it!](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}

  test:
    name: Test job
    runs-on: ubuntu-latest
    needs: notify
    environment:
      name: test
      url: https://github.com/${{ github.repository }}/releases/tag/${{ needs.notify.outputs.tag }}

    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: 1
          body: |
            Workflow ran for tag ${{ needs.notify.outputs.tag }}. The secret was "${{ secrets.A_SECRET }}".

      - name: Notify success in Slack
        uses: slackapi/slack-github-action@v1.15.0
        if: success()
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: |
            Tag [${{ needs.notify.outputs.tag }}](https://github.com/${{ github.repository }}/releases/tag/${{ needs.notify.outputs.tag }}) of ${{ github.repository }} was deployed! :tada:
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}

      - name: Notify failure in Slack
        uses: slackapi/slack-github-action@v1.15.0
        if: ! success()
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: |
            Tag [${{ needs.notify.outputs.tag }}](https://github.com/${{ github.repository }}/releases/tag/${{ needs.notify.outputs.tag }}) of ${{ github.repository }} deployment failed! :gummy-sad:

            [Check the job output](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
