name: Tests
on:
  pull_request:
  merge_group:

jobs:
  truetest:
    name: Always passes
    runs-on: ubuntu-latest
    steps:
      - run: true

  score_le_10:
    name: 'Score <= 10'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          sleep 60
          if [[ "$(< score.txt )" -le 10 ]]; then
            echo "ok"
          else
            echo "bad"
            exit 1
          fi

  score_gt_0:
    name: 'Score > 0'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          if [[ "$(< score.txt )" -gt 0 ]]; then
            echo "ok"
          else
            echo "bad"
            exit 1
          fi
